const constants = {
    AUTH_USER: 'AUTH_USER',
    SET_USER_DETAILS: 'SET_USER_DETAILS',
    SET_USER_BOOKS: 'SET_USER_BOOKS',
    APPEND_BOOK_TO_LIST: 'APPEND_BOOK_TO_LIST',
    TOGGLE_SELECTED_BOOK: 'TOGGLE_SELECTED_BOOK'
};

export default constants;
